### ISSUE TITLE
play/pause icon visible behind podcast icon

### ISSUE THREAD

**Issue by TheGeeKing** [NYRI4/Comfy-spicetify#13]
![image](https://user-images.githubusercontent.com/58857539/143298519-0582deb9-c1bb-4136-b2e5-14dcb67a5893.png)
![image](https://user-images.githubusercontent.com/58857539/143298528-291dc8b8-7184-47b0-a61e-75c1feedaf37.png)

easy fix is:
```css
.main-rootlist-statusIcons:not(:empty) {
  display: none;
}
```
but your CSS file is done in a way I prefer to let you do it :)
