### ISSUE TITLE
Main panel of screen hidden by CSS

### ISSUE THREAD

**Issue by ImperialOctopus** [NYRI4/Comfy-spicetify#26]
I've found that using this theme causes the main panel of any screen to be hidden, leaving only the side bars. I've narrowed it down to this line in app.css, which when commented out fixes the issue. My guess is the comma before .desktoproutes but I'm not completely sure what this line is meant to be doing!

Line 517 of Comfy-spicetify/app.css
``` css
.Root__main-view > div:first-of-type > div, .desktoproutes-homepage-takeover-ad-hptoComponent-parentContainer {
  display: none;
}
```

I'm using Spicetify 2.9.1 on Spotify for Windows 1.1.79.763.gc2965cdf.
